{% set name = "plumpy" %}
{% set version = "0.10.6" %}
{% set sha256 = "0746734b12f4a706f57ba9104225eb7dc5f2a1c4b68a70264497e58b59a26a34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [not py27]

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - frozendict
    - portalocker
    - pyyaml
    - tornado
    - future
    - kiwipy[rmq]>=0.2.0
    - enum34  # [py < 34]
    - backports.tempfile  # [py < 32]

test:
  imports:
    - plumpy

  source_files:
    - test

about:
  home: https://github.com/aiidateam/plumpy
  license: GPLv3, MIT
  license_file: LICENSE
  summary: "A python workflow library that supports multithreading, and RabbitMQ as a message broker for starting/stopping/monitoring tasks."
  dev_url: https://github.com/aiidateam/plumpy

extra:
  recipe-maintainers:
    - ltalirz
    - muhrin
