travis:
  secure:
    BINSTAR_TOKEN: v12l8U9mdwjKVPZkGy2a7HhB+u+kSDb/4vzrMNR0/b6XeXD/zLpwKG6Wwp8BIkz5CI1uIYgfOyUg7y/iCkhXlmrtj9eetq1+U5z9TrItQ2fqm02MScVq4QDdy8E8xE1rdD0QzmLFRJhfjJP1aFk0UgqJCwWe20nVVyZxQMPM3R2CU5aivviuZHfbJhb2TpVlN+Z5aqiJqEi02GnexCxlbqRPbrPH1kMw1kvKowo0sBC/ZvSVwQpHaG6U2GLBuAroqXmBBI81XMV10lQ+JvaolWbkhcSQuNDpgvIn6FFAfISHr35PoW46MPL2pEwuLCsEOcp8sMpyCVxB9z+dW3H4UZNFWJKjVECJVY3K2zhTG3bnSTKG6WNOM5CHZaa72Gwcx2WnaBRJoWd9APObr0Wn4yPbq85K96iVNOwD7QDDbTNVsHELO8MLMLUK8fWGpy4nK+axfj372XmNwQeYohpbixntiW7vW2seE7alOYI8aSe5yoX4kKnqb1EoQX5epoYpmf81Vmm9CMExs3ll8NMlMZTdFPsFLkNT22Zgj+xY63RUFWB6wCXzny4bh6ynS4ykwlTZA4zWkqRoeo4yS2wXJlkn50tC6u0W1YUi0mJoNIYAjxjlvWVDcY6bw57AA7JDfhieR4fhhMZLFA27BeryQ9/xWcGZA7zqgntUI4tVn3w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
