travis:
  secure:
    BINSTAR_TOKEN: r/CPbNuSNUlaC8e9e1g7Wkt1M4qSKJMs8TzlU8gk6FHCoTzbPpQcp5RrfTETfuOLGsHzXy8tE+u21c70kHIXcgtrDmMvyINJ4stUS5IKcrgfAjeyyb9GQahac8YQYuZa7jqwsKlqyzB10qZV35vhM/TqbQ5vUHv9VmQw3OUFAFAOala32RjL7ykE714on4lbYDUQ+7uXD6U80fhQNnpvXzAnsR0ALme7Z13Rhhw/1RuRqXtHHgs67V9T8Q7rP++1o6YG2SOG/ylauT+mnUhB/rW1+c0nCSIkXgcgnhnu25Gid2IuI/kJqAMMcvrTuAiIk166pTG6sLi1qNO7GKct06BHqsXUgJww6i0xM4LDtdSBVnxVHyoFhrzdAe3Igt4ESrceFeDe2Wd+hGop8fKJTpqzbmcz7BWoB59/Ry6+LbioluRbZ6P7rPzJxIQv6dUkbW60iRkfRq9tX3BfVbKXNQiD90MiUU2ZgvdqTKDj/NMewcuwU/a+PWvo2+pNv8PUTefw21Wg11kvH7X9nG/uqCoAeSAPAeizYP166PiCaGRYM220Edu85EzAgIHvkpszPwcStaD6IqeLpN6OyOgtwb7eNECn/am1Ma7B9RIKF6d/ujQWahqHHDBGPjAW5ZTSLM/Mt/CrpLalDFF9kFqaYhCOkgWBD44szHtKnp/RZHw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
